### ISSUE TITLE
IllegalArgumentException with CurveLineChart

### ISSUE THREAD

**Issue by Ola-jed** [hi-manshu/Charty#57]
I am using `CurveLineChart` to display some data.

Here is the code that displays the chart

```kt
CurveLineChart(
    modifier = Modifier
        .fillMaxWidth()
        .padding(vertical = 10.dp),
    lineData = lineData,
    chartColors = listOf(
        MaterialTheme.colors.secondary,
        MaterialTheme.colors.secondary
    ),
    lineColors = listOf(
        MaterialTheme.colors.primary,
        MaterialTheme.colors.primary
    )
)
// Where lineData is
// [LineData(xValue=Oct 27, 2022, yValue=0.0), LineData(xValue=Oct 28, 2022, yValue=0.0), ......]
// the other values have yValue equals to 0

```

When I run the app, I have the following stacktrace

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ola.myapp, PID: 7867
    java.lang.IllegalArgumentException
        at android.graphics.LinearGradient.nativeCreate(Native Method)
        at android.graphics.LinearGradient.createNativeInstance(LinearGradient.java:158)
        at android.graphics.Shader.getNativeInstance(Shader.java:191)
        at android.graphics.Paint.getNativeInstance(Paint.java:726)
        at android.graphics.BaseRecordingCanvas.drawPath(BaseRecordingCanvas.java:292)
        at androidx.compose.ui.graphics.AndroidCanvas.drawPath(AndroidCanvas.android.kt:242)
        at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawPath-GBMwjPU(CanvasDrawScope.kt:473)
        at androidx.compose.ui.node.LayoutNodeDrawScope.drawPath-GBMwjPU(Unknown Source:26)
        at androidx.compose.ui.graphics.drawscope.DrawScope.drawPath-GBMwjPU$default(DrawScope.kt:800)
        at com.himanshoe.charty.line.CurveLineChartKt$CurveLineChart$5.invoke(CurveLineChart.kt:187)
        at com.himanshoe.charty.line.CurveLineChartKt$CurveLineChart$5.invoke(CurveLineChart.kt:112)
        at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:104)
        at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
        at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:46)
        at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:105)
        at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:316)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:306)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:314)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:306)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:314)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:306)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:314)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:306)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:314)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:306)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:314)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:306)
        at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:839)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:314)
        at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:336)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:335)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2101)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:110)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:335)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:60)
        at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
```
It looks like this error is related to the gradient but I get the same error even if  I pass one color to the chart when using  `lineColor` and `chartColor`

**Comment by hi-manshu** [comment]
Hey thanks for letting me know will check!

**Comment by Ola-jed** [comment]
I have done some tests and i have noticed that this error appears when all the values are 0

**Comment by armanTabib** [comment]
It's 2024 and still facing this bug!

**Comment by armanTabib** [comment]
@Ola-jed 
This is part of my data and this bug happens: 
![image](https://github.com/hi-manshu/Charty/assets/139352271/13e5ca6c-500d-45b4-aa97-3de4f6b98d69)
